name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog:
    name: Check changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check changelog
        uses: MetaMask/github-tools/.github/actions/check-changelog@d0f155aad5d7b5403d29a094c2f752238bf43237 # v1.18.2
        with:
          base-branch: ${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.head_ref }}
          labels: ${{ toJSON(github.event.pull_request.labels) }}
          pr-number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
