name: Publish to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        description:
          'Subdirectory of the site to publish into; the deployment replaces the
          entire site'
        required: true
        type: string
      artifact_name:
        description: 'Name of artifact to download'
        required: true
        type: string

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact_name }}
          path: _site/${{ inputs.destination_dir }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
